### ISSUE TITLE
Fixa footer så den är kompatibel med sidebar

### ISSUE THREAD

**Issue by liinnjohansson** [95olibod/Calender-groupComposition#33]
Sidebar ska ligga bakom bild 1 och 2 (svart och gul) i footer och framför bild 3 (transparent grå).

**Comment by 95olibod** [comment]
Olivia och Linn - flytta över bilden till main? - fråga David.

**Comment by liinnjohansson** [comment]
Footer ska inte ha bakgrundsfärg, eftersom den bakersta bilden ska vara transparent. Glappet mellan, där det blir vitt får fixas med padding på kalendern, mest troligt!
